In [1]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
data=pd.read_csv('car_evaluation.csv')
data.columns=['buying', 'maint','doors','persons','lug_boot','safety','class']

In [3]:
data.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [9]:
X=data[['buying','maint','safety']].values

In [16]:
y=data[['class']].values

In [6]:
Le=LabelEncoder()

In [13]:
for i in range(len(X[0])):
    X[:,i]=Le.fit_transform(X[:,i])

In [14]:
X

array([[3, 3, 2],
       [3, 3, 0],
       [3, 3, 1],
       ...,
       [1, 1, 1],
       [1, 1, 2],
       [1, 1, 0]], dtype=object)

In [17]:
for j in range(len(y[0])):
    y[:,j]=Le.fit_transform(y[:,j])

In [28]:
y=y.astype('int')

In [29]:
y

array([[2],
       [2],
       [2],
       ...,
       [2],
       [1],
       [3]])

In [31]:
knn=neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')

In [32]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

In [34]:
knn.fit(X_train,y_train.ravel())

KNeighborsClassifier(n_neighbors=25)

In [35]:
prediction=knn.predict(X_test)

In [36]:
accuracy=metrics.accuracy_score(y_test,prediction)

In [37]:
prediction

array([2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 0, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 0, 2, 0, 2, 0, 3, 0, 2, 2, 2, 1, 2, 0, 2, 2, 0, 2, 2, 3,
       0, 2, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 3, 0, 2, 2,
       2, 2, 3, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 3, 2, 2, 2, 0, 0, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 0,
       2, 2, 0, 2, 2, 1, 2, 2, 2, 2, 3, 2, 2, 0, 0, 0, 3, 2, 2, 3, 2, 2,
       1, 2, 2, 0, 2, 2, 2, 2, 3, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 0, 1, 2, 2, 3, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0,
       2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2,
       2, 0, 2, 0, 3, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 3, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,

In [38]:
accuracy

0.7398843930635838

In [47]:
y[1500]

array([0])

In [48]:
knn.predict(X)[1500]

0